# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import static
from PyQt5.QtGui import QWheelEvent, QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication, Qt
from PyQt5.QtWidgets import QSystemTrayIcon, QMenu, QAction
from PyQt5.QtWidgets import  QGraphicsScene, QGraphicsView, QGraphicsPixmapItem, QDesktopWidget

class ImageView(QGraphicsView):
    def __init__(self):
        super().__init__()
        self.image = None
        self.image_item = None
        self.current_angle = 0
        self.scene = QGraphicsScene(self)
        self.setScene(self.scene)
        self.setDragMode(QGraphicsView.RubberBandDrag)
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

    def loadImage(self):
        self.image_item = QGraphicsPixmapItem(self.image)
        self.image_item.setFlag(QGraphicsPixmapItem.ItemIsMovable)
        self.scene.addItem(self.image_item)
        self.fitInView(self.image_item, Qt.KeepAspectRatio)
        self.show()

    def wheelEvent(self, event: QWheelEvent):
        if event.angleDelta().y() > 0:
            self.scale(1.1, 1.1)
        else:
            self.scale(1 / 1.1, 1 / 1.1)

    def update_image(self):
        self.scene.clear()
        self.image_item = QGraphicsPixmapItem(self.image)
        self.image_item.setFlag(QGraphicsPixmapItem.ItemIsMovable)
        self.scene.addItem(self.image_item)
        self.image_item.setOffset(self.sceneRect().center() - self.image_item.boundingRect().center())
        self.fitInView(self.image_item, Qt.KeepAspectRatio)
        self.show()

    def rotate_image(self):
        if self.image_item:
            self.current_angle += 90
            self.image_item.setRotation(self.current_angle)
            bounding_rect = self.image_item.boundingRect()
            self.image_item.setTransformOriginPoint(bounding_rect.center())
            self.center_image()
            if self.current_angle >= 360:
                self.current_angle = 0

    def center_image(self):
        if self.image_item:
            view_center = self.viewport().rect().center()
            scene_center = self.mapToScene(view_center)
            self.image_item.setPos(scene_center - self.image_item.boundingRect().center())

    def resizeEvent(self, event):
        super().resizeEvent(event)
        if self.image_item:
            self.fitInView(self.image_item, Qt.KeepAspectRatio)

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self):
        self.tray = QSystemTrayIcon()
        self.tray.setIcon(QIcon(':/logo.png'))
        showAction = QAction("打开", self, triggered = self.Show)
        quitAction = QAction("退出", self, triggered = QCoreApplication.instance().quit)
        self.trayMenu = QMenu(self)
        self.trayMenu.addAction(showAction)
        self.trayMenu.addSeparator()
        self.trayMenu.addAction(quitAction)
        self.tray.setContextMenu(self.trayMenu)
        self.tray.show()
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_prev = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_prev.sizePolicy().hasHeightForWidth())
        self.btn_prev.setSizePolicy(sizePolicy)
        self.btn_prev.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon1)
        self.btn_prev.setObjectName("btn_prev")
        self.horizontalLayout.addWidget(self.btn_prev)
        self.img_name = QtWidgets.QLabel(self.centralwidget)
        self.img_name.setAlignment(QtCore.Qt.AlignCenter)
        self.img_name.setObjectName("img_name")
        self.horizontalLayout.addWidget(self.img_name)
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        self.btn_next.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon2)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.img_idx_now = QtWidgets.QLabel(self.centralwidget)
        self.img_idx_now.setObjectName("img_idx_now")
        self.horizontalLayout.addWidget(self.img_idx_now)
        self.img_idx_seg = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_idx_seg.sizePolicy().hasHeightForWidth())
        self.img_idx_seg.setSizePolicy(sizePolicy)
        self.img_idx_seg.setObjectName("img_idx_seg")
        self.horizontalLayout.addWidget(self.img_idx_seg)
        self.img_idx_total = QtWidgets.QLabel(self.centralwidget)
        self.img_idx_total.setObjectName("img_idx_total")
        self.horizontalLayout.addWidget(self.img_idx_total)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.img_idx_input = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_idx_input.sizePolicy().hasHeightForWidth())
        self.img_idx_input.setSizePolicy(sizePolicy)
        self.img_idx_input.setAlignment(QtCore.Qt.AlignCenter)
        self.img_idx_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.img_idx_input.setMaximum(999999999)
        self.img_idx_input.setObjectName("img_idx_input")
        self.horizontalLayout.addWidget(self.img_idx_input)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btn_xuanzhuan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_xuanzhuan.sizePolicy().hasHeightForWidth())
        self.btn_xuanzhuan.setSizePolicy(sizePolicy)
        self.btn_xuanzhuan.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/xuanzhuan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_xuanzhuan.setIcon(icon3)
        self.btn_xuanzhuan.setObjectName("btn_xuanzhuan")
        self.horizontalLayout.addWidget(self.btn_xuanzhuan)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listView = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.listView.setItemAlignment(QtCore.Qt.AlignLeading)
        self.listView.setObjectName("listView")
        self.graphicsView = ImageView()
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout_2.addWidget(self.listView)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.action_dir = QtWidgets.QAction(self)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_dir.setIcon(icon4)
        self.action_dir.setObjectName("action_dir")
        self.menu.addAction(self.action_dir)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def Center(self):
        screen = QDesktopWidget().screenGeometry()
        window_size = self.geometry()
        self.move(int((screen.width() - window_size.width()) / 2) , int((screen.height() - window_size.height()) / 2))

    def Show(self):
        self.showNormal()
        self.activateWindow()
        self.setWindowFlags(QtCore.Qt.Window)
        self.Center()
        self.show()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("", "图片可视化"))
        self.btn_prev.setToolTip(_translate("", "上一张"))
        self.btn_prev.setShortcut(_translate("", "Left"))
        self.img_name.setText(_translate("", "未加载图片"))
        self.btn_next.setToolTip(_translate("", "下一张"))
        self.btn_next.setShortcut(_translate("", "Right"))
        self.img_idx_now.setText(_translate("", "0"))
        self.img_idx_seg.setText(_translate("", "/"))
        self.img_idx_total.setText(_translate("", "0"))
        self.btn_xuanzhuan.setToolTip(_translate("", "旋转"))
        self.btn_xuanzhuan.setShortcut(_translate("", "R"))
        self.menu.setTitle(_translate("", "文件"))
        self.action_dir.setText(_translate("", "选择目录"))
        self.action_dir.setShortcut(_translate("", "Ctrl+O"))

