# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import static
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtGui import QWheelEvent, QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QSystemTrayIcon, QMenu, QAction
from PyQt5.QtWidgets import  QGraphicsScene, QGraphicsView, QGraphicsPixmapItem, QDesktopWidget


class ImageView(QGraphicsView):
    def __init__(self):
        super().__init__()
        self.image = None
        self.image_item = None
        self.scene = QGraphicsScene(self)
        self.setScene(self.scene)
        self.setDragMode(QGraphicsView.RubberBandDrag)
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

    def loadImage(self):
        self.image_item = QGraphicsPixmapItem(self.image)
        self.image_item.setFlag(QGraphicsPixmapItem.ItemIsMovable)
        self.scene.addItem(self.image_item)
        self.show()

    def wheelEvent(self, event: QWheelEvent):
        if event.angleDelta().y() > 0:
            self.scale(1.1, 1.1)
        else:
            self.scale(1 / 1.1, 1 / 1.1)

    def update_image(self):
        self.scene.clear()
        self.image_item = QGraphicsPixmapItem(self.image)
        self.image_item.setFlag(QGraphicsPixmapItem.ItemIsMovable)
        self.scene.addItem(self.image_item)
        self.image_item.setOffset(self.sceneRect().center() - self.image_item.boundingRect().center())
        self.show()

class MainUI(QtWidgets.QMainWindow):
    def setupUi(self):
        self.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)

        self.tray = QSystemTrayIcon()
        self.tray.setIcon(QIcon(':/logo.png'))
        showAction = QAction("打开", self, triggered = self.Show)
        quitAction = QAction("退出", self, triggered = QCoreApplication.instance().quit)
        self.trayMenu = QMenu(self)
        self.trayMenu.addAction(showAction)
        self.trayMenu.addSeparator()
        self.trayMenu.addAction(quitAction)
        self.tray.setContextMenu(self.trayMenu)
        self.tray.show()

        self.centralwidget = QtWidgets.QWidget(self)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_prev = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon1)
        self.horizontalLayout.addWidget(self.btn_prev)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_img_name = QtWidgets.QLabel(self.centralwidget)
        self.horizontalLayout.addWidget(self.label_img_name)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon2)
        self.horizontalLayout.addWidget(self.btn_next)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalLayout.addWidget(self.line)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_img_idx_now = QtWidgets.QLabel(self.centralwidget)
        self.horizontalLayout.addWidget(self.label_img_idx_now)
        self.label_g = QtWidgets.QLabel(self.centralwidget)
        self.horizontalLayout.addWidget(self.label_g)
        self.label_img_idx_total = QtWidgets.QLabel(self.centralwidget)
        self.horizontalLayout.addWidget(self.label_img_idx_total)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.graphicsView = ImageView()
        self.graphicsView.setDragMode(QGraphicsView.RubberBandDrag)
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.setStatusBar(self.statusbar)
        self.action_open_img_dir = QtWidgets.QAction(self)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/open_dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open_img_dir.setIcon(icon3)
        self.action_version = QtWidgets.QAction(self)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_version.setIcon(icon5)
        self.menu.addAction(self.action_open_img_dir)
        self.menu_2.addAction(self.action_version)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def Center(self):
        screen = QDesktopWidget().screenGeometry()
        window_size = self.geometry()
        self.move(int((screen.width() - window_size.width()) / 2) , int((screen.height() - window_size.height()) / 2))

    def Show(self):
        self.showNormal()
        self.activateWindow()
        self.setWindowFlags(QtCore.Qt.Window)
        self.Center()
        self.show()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("", "图片可视化"))
        self.btn_prev.setShortcut(_translate("", "Left"))
        self.label_img_name.setText(_translate("", "图片名字"))
        self.btn_next.setShortcut(_translate("", "Right"))
        self.label_img_idx_now.setText(_translate("", "0"))
        self.label_g.setText(_translate("", "/"))
        self.label_img_idx_total.setText(_translate("", "0"))
        self.menu.setTitle(_translate("", "选项"))
        self.menu_2.setTitle(_translate("", "关于"))
        self.action_open_img_dir.setText(_translate("", "选择图片目录"))
        self.action_open_img_dir.setShortcut(_translate("", "Ctrl+O"))
        self.action_version.setText(_translate("", "版本"))

